# Menggunakan image dasar Python 3.12 slim agar ringan
FROM python:3.12-slim

# Menetapkan direktori kerja di dalam container
WORKDIR /app

# Menginstal dependensi sistem yang dibutuhkan untuk scikit-learn/pandas
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Menyalin file requirements ke dalam container
COPY requirements.txt .

# Menginstal library Python
RUN pip install --no-cache-dir -r requirements.txt

# Menyalin file model dan script lainnya (jika perlu)
# Asumsi model.pkl berada di direktori yang sama
COPY . .

# Mengekspos port 8080 (port default MLflow model serving)
EXPOSE 8080

# Menjalankan MLflow model serve
CMD ["mlflow", "models", "serve", "-m", "random_forest_ci", "--host", "0.0.0.0", "--port", "8080"]
