name: heart-disease-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - mlflow==2.19.0
    - dagshub
    - matplotlib
    - seaborn
